
SRC_ROOT=../../../../..
include $(SRC_ROOT)/freemasonBuild/freemason/4/main

define SPECS
	(PLATFORM=rv-win32 DEBUG=1)
#	(PLATFORM=rv-win32 OPT=1)
	(PLATFORM=rv-linux-x86 DEBUG=1)
#	(PLATFORM=rv-linux-x86 OPT=1)
	(PLATFORM=rv-linux-ppc DEBUG=1)
#	(PLATFORM=rv-linux-ppc OPT=1)
	(PLATFORM=rv-avatar-v232  DEBUG=1)
endef

#----------------------------------------------------------------------------------------------

include $(MK)/defs
include $(MK)/rules
