
define CC_PP_DEFS +=
	DOCTOPT_USE_BOOST_REGEX
	BOOST_ALL_NO_LIB
endef

#----------------------------------------------------------------------------------------------

define CC_INCLUDE_DIRS +=
endef

#----------------------------------------------------------------------------------------------

CC_SRC_DIR=$(DOCOPT_ROOT)

define CC_SRC_FILES +=
	docopt.cpp
endef
