
define CC_PP_DEFS +=
endef

#----------------------------------------------------------------------------------------------

define CC_INCLUDE_DIRS +=
endef

#----------------------------------------------------------------------------------------------

CC_SRC_DIR=$(NLOHMANN_JSON_ROOT)/src

define CC_SRC_FILES +=
endef
