
define CC_PP_DEFS +=
	GTEST_HAS_TR1_TUPLE=0
	BOOST_ALL_NO_LIB
endef

#----------------------------------------------------------------------------------------------

define CC_INCLUDE_DIRS +=
endef

#----------------------------------------------------------------------------------------------

define CC_SRC_FILES +=
	test1.cpp
	test2a.cpp
	test2b.cpp
	test3.cpp
endef
