
define CC_PP_DEFS +=
endef

#----------------------------------------------------------------------------------------------

define CC_INCLUDE_DIRS +=
endef

#----------------------------------------------------------------------------------------------

CC_SRC_DIR=$(YAML_CPP_ROOT)/src

define CC_SRC_FILES +=
	binary.cpp
	convert.cpp
	directives.cpp
	emit.cpp
	emitfromevents.cpp
	emitter.cpp
	emitterstate.cpp
	emitterutils.cpp
	exceptions.cpp
	exp.cpp
	memory.cpp
	node.cpp
	node_data.cpp
	nodebuilder.cpp
	nodeevents.cpp
	null.cpp
	ostream_wrapper.cpp
	parse.cpp
	parser.cpp
	regex_yaml.cpp
	scanner.cpp
	scanscalar.cpp
	scantag.cpp
	scantoken.cpp
	simplekey.cpp
	singledocparser.cpp
	stream.cpp
	tag.cpp
	contrib/graphbuilder.cpp
	contrib/graphbuilderadapter.cpp
endef
